apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: httpbin-ingress-route
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`okta.hellman.oxygen.dfds.cloud`)
    kind: Rule
    services:
    - name: httpbin
      port: 8080