apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
  labels:
    scrape-service-metrics: "true"
  name: traefik-okta-test
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: web
    nodePort: 31080
    port: 80
    protocol: TCP
    targetPort: 80
  - name: admin
    nodePort: 31081
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    k8s-app: traefik-okta-test
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
