apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage-backend
  labels:
    app: backstage
    component: backend
    project: developerautomation
    department: cloudengineering
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
      component: backend
  template:
    metadata:
      labels:
        app: backstage
        component: backend
        project: developerautomation
        department: cloudengineering        
    spec:
      containers:
      - name: backend
        image: 579478677147.dkr.ecr.eu-central-1.amazonaws.com/selfservice/backstage-backend:#(Build.BuildId)
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7000
          name: backend
          protocol: TCP
        envFrom:
        - configMapRef:
            name: backstage-proxy-endpoints
        env:
        - name: AUTH_MICROSOFT_CLIENT_ID
          value: #(AUTH_MICROSOFT_CLIENT_ID)
        - name: AUTH_MICROSOFT_CLIENT_SECRET
          value: #(AUTH_MICROSOFT_CLIENT_SECRET)
        - name: AUTH_MICROSOFT_TENANT_ID
          value: #(AUTH_MICROSOFT_TENANT_ID)
        - name: KAFKA_CLUSTER
          value: #(KAFKA_CLUSTER)
        - name: KAFKA_USERNAME
          value: #(KAFKA_USERNAME)
        - name: KAFKA_PASSWORD
          value: #(KAFKA_PASSWORD)
        - name: HELLMAN_SERVICE_ACCOUNT_TOKEN
          value: #(HELLMAN_SERVICE_ACCOUNT_TOKEN)
        - name: GITHUB_PRIVATE_TOKEN
          valueFrom:
            secretKeyRef:
              name: backstage-third-party-credentials
              key: github_token
        - name: AZUREDEVOPS_AUTH_CREDENTIALS
          valueFrom:
            secretKeyRef:
              name: backstage-third-party-credentials
              key: azuredevops_token
        - name: DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: backstage-rdspostgresql-conn
              key: endpoint
        - name: DATABASE_PORT
          valueFrom:
            secretKeyRef:
              name: backstage-rdspostgresql-conn
              key: port
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: backstage-rdspostgresql-conn
              key: username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backstage-rdspostgresql-conn
              key: password
        resources: {}
