app:
  title: Backstage DFDS
  baseUrl: http://backstage.dfds.cloud:3000

backend:
  baseUrl: http://backstage.dfds.cloud:7000
  listen: 0.0.0.0:7000
  cors:
    origin: http://backstage.dfds.cloud:3000
    methods: [GET, POST, PUT, DELETE]
    credentials: true

proxy:
  '/circleci/api':
    target: 'https://circleci.com/api/v1.1'
    changeOrigin: true
    pathRewrite:
      '^/proxy/circleci/api/': '/'

organization:
  name: DFDS

techdocs:
  storageUrl: https://techdocs-mock-sites.storage.googleapis.com
