app:
  title: Backstage DFDS
  baseUrl: https://backstage.dfds.cloud

backend:
  baseUrl: https://backstage.dfds.cloud/backend
  listen: 0.0.0.0:7000
  cors:
    origin: [https://backstage.dfds.cloud, http://localhost:3000, http://localhost:7000]
    methods: [GET, POST, PUT, DELETE]
    credentials: true

proxy:
  '/circleci/api':
    target: 'https://circleci.com/api/v1.1'
    changeOrigin: true
    pathRewrite:
      '^/proxy/circleci/api/': '/'

organization:
  name: DFDS

techdocs:
  storageUrl: https://techdocs-mock-sites.storage.googleapis.com
