#Setup build image
FROM node:lts-buster

# Set container filesystem to /build (and create folder if it doesn't exist)
WORKDIR /backstage

#Copy files to container file system.
COPY ./packages/backend ./packages/backend
COPY ./packages/catalog-model ./packages/catalog-model
COPY ./packages/config-loader ./packages/config-loader
COPY ./app-config.yaml ./app-config.yaml
COPY ./package.json ./package.json
COPY ./yarn.lock ./yarn.lock

RUN yarn install

WORKDIR /backstage/packages/backend
CMD yarn start