version: '3'

services:
  database:
    image: postgres:latest
    networks:
      development:
        aliases:
          - database
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=p"

networks:
  development:
    external: true