#Setup build image
FROM node:lts-buster

# Set container filesystem to /build (and create folder if it doesn't exist)
WORKDIR /backstage

#Copy files to container file system.
COPY ./packages/backend ./packages/backend
COPY ./packages/backend-common ./packages/backend-common
COPY ./packages/config ./packages/config
COPY ./packages/config-loader ./packages/config-loader
COPY ./plugins/auth-backend ./plugins/auth-backend
COPY ./plugins/catalog-backend ./plugins/catalog-backend
COPY ./plugins/identity-backend ./plugins/identity-backend
COPY ./plugins/proxy-backend ./plugins/proxy-backend
COPY ./plugins/rollbar-backend ./plugins/rollbar-backend
COPY ./plugins/scaffolder-backend ./plugins/scaffolder-backend
COPY ./plugins/sentry-backend ./plugins/sentry-backend
COPY ./plugins/techdocs-backend ./plugins/techdocs-backend
COPY ./packages/catalog-model ./packages/catalog-model
COPY ./packages/cli ./packages/cli

COPY ./app-config.yaml ./app-config.yaml
COPY ./package.json ./package.json
COPY ./yarn.lock ./yarn.lock
COPY ./tsconfig.json ./tsconfig.json

RUN yarn install

WORKDIR /backstage/packages/backend
CMD yarn start