apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: traefik-okta-test
    release: traefik-okta-test
  name: traefik-okta-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik-okta-test
      release: traefik-okta-test
  template:
    metadata:
      labels:
        app: traefik-okta-test
        release: traefik-okta-test
    spec:
      containers:
      - args:
        - --api
        - --api.insecure
        - --api.dashboard=true
        - --accesslog
        - --log.level=DEBUG
        - --metrics.prometheus
        - --accessLog.format=json
        - --accessLog.filters.statusCodes='300-399,400-499,500-599'
        - --ping=true
        - --global.checknewversion=true
        - --entryPoints.traefik.address=:8080
        - --entryPoints.web.address=:80
        - --entryPoints.websecure.address=:443
        - --providers.kubernetescrd=true
        #- --providers.kubernetesingress=true

        image: traefik:2.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        name: traefik-okta-test
        ports:
          - name: web
            containerPort: 80
          - name: websecure
            containerPort: 4443
          - name: admin
            containerPort: 8080
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /ping
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: traefik-v2-sa
      serviceAccountName: traefik-v2-sa
      terminationGracePeriodSeconds: 60