apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
  labels:
    scrape-service-metrics: "true"
  name: traefik-okta-test
spec:
  externalTrafficPolicy: Cluster
  ports:
    - protocol: TCP
      name: web
      port: 80
      targetPort: 80
      nodePort: 31080

    - protocol: TCP
      name: admin
      port: 8080
      targetPort: 8080
      nodePort: 31081

    - protocol: TCP
      name: websecure
      port: 4443

  selector:
    app: traefik-okta-test
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
