version: '3.9'
services:
  database:
    image: postgres:latest
    container_name: backstage-db
    ports:
      - '5432:5432'
    env_file:
      - .env  
  backstage-backend:
    depends_on:
      - database
    image: node:14
    working_dir: /app
    command: >
        yarn start-backend
    volumes:
      - ../:/app
    env_file:
      - .env
    ports:
      - '7000:7000'
    links:
      - database
      - kafka
  backstage-frontend:
    depends_on:
      - backstage-backend
    image: node:14
    working_dir: /app
    command: >
        yarn start
    volumes:
      - ../:/app
    ports:
      - 3000:3000
    env_file:
      - .env
    extra_hosts: 
      - "localdev:0.0.0.0"
  kafka:
    image: spotify/kafka
    ports:
      - '2181:2181'
      - '9092:9092'
    environment:
      - 'ADVERTISED_HOST=localhost'
      - 'ADVERTISED_PORT=9092'
      - 'AUTO_CREATE_TOPICS=true'
